Handle WebView inflate exceptions
Like:

android.view.InflateException: Binary XML file line #17: Error inflating class android.webkit.WebView
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to find donor package: com.android.chrome