Revert "Updated AndroidX" / Lifecycle
This reverts commit eebdff9fdabf21a72526cf42913bab9963bfb39d.

java.lang.AbstractMethodError: abstract method "androidx.lifecycle.ViewModel androidx.lifecycle.ViewModelProvider$Factory.create(kotlin.reflect.KClass, androidx.lifecycle.viewmodel.CreationExtras)"
	at androidx.lifecycle.viewmodel.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel_release(ViewModelProviderImpl.kt:69)
	at androidx.lifecycle.viewmodel.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel_release$default(ViewModelProviderImpl.kt:47)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.android.kt:91)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.android.kt:109)
	at leakcanary.internal.ViewModelClearedWatcher$Companion.install(ViewModelClearedWatcher.kt:61)
	at leakcanary.internal.AndroidXFragmentDestroyWatcher.invoke(AndroidXFragmentDestroyWatcher.kt:66)
	at leakcanary.internal.AndroidXFragmentDestroyWatcher.invoke(AndroidXFragmentDestroyWatcher.kt:25)
	at leakcanary.FragmentAndViewModelWatcher$lifecycleCallbacks$1.onActivityCreated(FragmentAndViewModelWatcher.kt:59)
	at android.app.Application.dispatchActivityCreated(Application.java:189)
	at android.app.Activity.onCreate(Activity.java:936)
	at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.kt:73)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:359)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:216)
	at eu.faircode.email.ActivityBase.onCreate(ActivityBase.java:421)
	at eu.faircode.email.ActivityMain.onCreate(ActivityMain.java:200)
	at android.app.Activity.performCreate(Activity.java:5937)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)